services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinel-frontend-dev

    # âš¡ PERINTAH PENTING: Memaksa jalan di mode dev
    command: npm run dev

    ports:
      - "3000:3000"

    environment:
      # Agar codingan berubah otomatis (Hot Reload) di Windows
      - WATCHPACK_POLLING=true
      - NODE_ENV=development

    volumes:
      - .:/app
      - /app/node_modules # <--- INI WAJIB ADA!
      - /app/.next

    # Agar terminal interaktif (bisa Ctrl+C)
    stdin_open: true
    tty: true
